# yaml-language-server: $schema=../../schema/v1/kinds/group.schema.json
apiVersion: powerloom.app/v1
kind: Group
metadata:
  name: senior-engineers
  ou_path: /acme/engineering
spec:
  display_name: Senior Engineers
