# generated by datamodel-codegen:
#   filename:  convention.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ApiVersion(StrEnum):
    """
    v2.0.0 fixes the apiVersion to a single canonical form. No monorepo backward-compat alias.
    """

    powerloom_app_v2 = 'powerloom.app/v2'


class ResourceName(RootModel[str]):
    root: str = Field(
        ..., max_length=63, min_length=1, pattern='^[a-z0-9][a-z0-9-]{0,62}$'
    )
    """
    DNS-compatible slug. Lowercase letters, digits, hyphens; must start with alnum; 1–63 chars.
    """


class Uuid(RootModel[str]):
    root: str = Field(
        ...,
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )


class DisplayName(RootModel[str]):
    root: str = Field(..., max_length=255, min_length=1)


class OuPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})*$'
    )
    """
    Absolute OU path, e.g. /acme/engineering/platform.
    """


class AgentPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})+$'
    )
    """
    Absolute path to a resource: /{org}/{ou...}/{name}.
    """


class PrincipalRef(RootModel[str]):
    root: str = Field(..., pattern='^(user:[^\\s]+@[^\\s]+|group:/.+|agent:/.+)$')
    """
    One of 'user:<email>', 'group:<group_path>', or 'agent:<agent_path>'.
    """


class ScopeRef(RootModel[str]):
    root: str = Field(
        ..., max_length=128, min_length=2, pattern='^[a-z0-9][a-z0-9_.-]*[a-z0-9]$'
    )
    """
    Dotted-path reference to a Scope (e.g., 'home.research.infra'). Resolves within the containing OU.
    """


class PrimitiveRef(StrEnum):
    """
    Name of one of the six v2 root primitives. Used in compose-expression slot tags.
    """

    Entity = 'Entity'
    Event = 'Event'
    Relation = 'Relation'
    Process = 'Process'
    Scope = 'Scope'
    Policy = 'Policy'


class KindRef(RootModel[str]):
    root: str = Field(..., pattern='^[A-Z][A-Za-z0-9]*(\\.[a-z0-9][a-z0-9_-]*)*$')
    """
    Qualified kind name: either a stdlib kind (e.g. 'Agent', 'Workflow') or a user-composed kind in a namespace (e.g. 'legal.ContractClause').
    """


class ComposeSlot1(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef
    extends: KindRef | None = None
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot2(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef | None = None
    extends: KindRef
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot(RootModel[ComposeSlot1 | ComposeSlot2]):
    root: ComposeSlot1 | ComposeSlot2
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """


class Item(RootModel[str]):
    root: str = Field(..., max_length=256, min_length=1)


class ConventionBody(BaseModel):
    """
    The convention's content. summary is required free text; items is an optional structured checklist; references link to other governance primitives this convention codifies or constrains.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    summary: str = Field(..., max_length=4096, min_length=1)
    """
    The rule itself, written for humans. Markdown allowed. Keep short — the body of a convention is its essence; reference docs go elsewhere.
    """
    items: list[Item] | None = Field([], validate_default=True)
    """
    Optional ordered checklist or rule list. Each item is a short label suitable for a UI checkbox; the prose explanation of each item lives in summary.
    """


class EnforcementMode(StrEnum):
    """
    How the convention is enforced. advisory: stored + visible but no runtime check. warn: violations log + surface in audit but don't block. enforce: violations block the action.
    """

    advisory = 'advisory'
    warn = 'warn'
    enforce = 'enforce'


class ConventionStatus(StrEnum):
    """
    Lifecycle state. active: visible + enforced per enforcement_mode. archived: historical record, no enforcement; preserved for audit + concept-promotion provenance.
    """

    active = 'active'
    archived = 'archived'


class Kind(StrEnum):
    concept = 'concept'
    type_definition = 'type_definition'
    stdlib = 'stdlib'


class ConventionReference(BaseModel):
    """
    Optional cross-reference to a concept or type-definition this convention codifies. v064 ships the field shape; cross-validation against existing concept_id / type_definition_id rows happens at apply time on the engine.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    id: str | None = Field(
        None,
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )
    """
    UUID for concept / type_definition kinds. Null for stdlib kind references where name carries the identity.
    """
    name: str | None = Field(None, max_length=128)


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: ResourceName
    ou_path: OuPath


class Spec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: DisplayName
    description: str | None = Field(None, max_length=2048)
    applies_to_scope_ref: ScopeRef
    """
    Primary scope this convention governs. Resources within this scope (or its descendants per the scope tree) check the convention when relevant actions fire.
    """
    additional_scope_refs: list[ScopeRef] | None = Field([], validate_default=True)
    """
    Rare — additional scopes the convention also governs. Most conventions need only the primary applies_to_scope_ref; populate this when one rule legitimately spans multiple scope subtrees.
    """
    body: ConventionBody
    enforcement_mode: EnforcementMode | None = 'advisory'
    status: ConventionStatus | None = 'active'
    references: list[ConventionReference] | None = Field([], validate_default=True)
    """
    Optional cross-references to concepts (Chomskian R18 — convention codifies a stabilized regularity), type_definitions (convention constrains a type), or stdlib kinds.
    """


class Convention(BaseModel):
    """
    A human-codified organizational rule scoped to a slice of the org. Conventions are top-down authored intent — operators write them, version-control them, review them — distinct from procedural memory templates (which are bottom-up reinforced from observed runs). Each Convention names a body of guidance plus an enforcement_mode (advisory / warn / enforce) that the engine and downstream agents respect when the convention's scope matches. Derivation: compose(Policy[intent], Scope[applies_to]). Cross-references concept_ids (when the convention codifies a stabilized concept per Chomskian R18) and type_definitions (when it constrains how a type composes).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    apiVersion: ApiVersion
    kind: Literal['Convention']
    metadata: Metadata
    spec: Spec
