# generated by datamodel-codegen:
#   filename:  failure-recovery-frame.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ActionAttempted(BaseModel):
    """
    Frame element 1: the kind of action this frame matches. summary is required free text; process_kind narrows by Process primitive's process_kind field if set; matcher_pattern is an optional regex applied to the action's structured payload.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    summary: str = Field(..., max_length=1024, min_length=1)
    process_kind: str | None = Field(None, max_length=128)
    """
    Optional narrowing: only match actions whose enclosing Process has this process_kind (e.g., 'agent_runtime', 'skill_invocation', 'mcp_server').
    """
    matcher_pattern: str | None = Field(None, max_length=1024)
    """
    Optional regex applied to the action's serialized payload at match time. Engine compiles + caches.
    """


class Step(RootModel[str]):
    root: str = Field(..., max_length=1024, min_length=1)


class Provenance(StrEnum):
    """
    Where this frame came from. v057 ships only operator_authored; distilled_from_episodic lights up at v058+ when consolidation can promote observation conventions into frames.
    """

    operator_authored = 'operator_authored'
    distilled_from_episodic = 'distilled_from_episodic'
    imported_template = 'imported_template'


class ApiVersion(StrEnum):
    """
    v2.0.0 fixes the apiVersion to a single canonical form. No monorepo backward-compat alias.
    """

    powerloom_app_v2 = 'powerloom.app/v2'


class ResourceName(RootModel[str]):
    root: str = Field(
        ..., max_length=63, min_length=1, pattern='^[a-z0-9][a-z0-9-]{0,62}$'
    )
    """
    DNS-compatible slug. Lowercase letters, digits, hyphens; must start with alnum; 1–63 chars.
    """


class Uuid(RootModel[str]):
    root: str = Field(
        ...,
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )


class DisplayName(RootModel[str]):
    root: str = Field(..., max_length=255, min_length=1)


class OuPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})*$'
    )
    """
    Absolute OU path, e.g. /acme/engineering/platform.
    """


class AgentPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})+$'
    )
    """
    Absolute path to a resource: /{org}/{ou...}/{name}.
    """


class PrincipalRef(RootModel[str]):
    root: str = Field(..., pattern='^(user:[^\\s]+@[^\\s]+|group:/.+|agent:/.+)$')
    """
    One of 'user:<email>', 'group:<group_path>', or 'agent:<agent_path>'.
    """


class ScopeRef(RootModel[str]):
    root: str = Field(
        ..., max_length=128, min_length=2, pattern='^[a-z0-9][a-z0-9_.-]*[a-z0-9]$'
    )
    """
    Dotted-path reference to a Scope (e.g., 'home.research.infra'). Resolves within the containing OU.
    """


class PrimitiveRef(StrEnum):
    """
    Name of one of the six v2 root primitives. Used in compose-expression slot tags.
    """

    Entity = 'Entity'
    Event = 'Event'
    Relation = 'Relation'
    Process = 'Process'
    Scope = 'Scope'
    Policy = 'Policy'


class KindRef(RootModel[str]):
    root: str = Field(..., pattern='^[A-Z][A-Za-z0-9]*(\\.[a-z0-9][a-z0-9_-]*)*$')
    """
    Qualified kind name: either a stdlib kind (e.g. 'Agent', 'Workflow') or a user-composed kind in a namespace (e.g. 'legal.ContractClause').
    """


class ComposeSlot1(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef
    extends: KindRef | None = None
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot2(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef | None = None
    extends: KindRef
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot(RootModel[ComposeSlot1 | ComposeSlot2]):
    root: ComposeSlot1 | ComposeSlot2
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """


class ErrorCategory(StrEnum):
    """
    Coarse categorical label for the failure. Frames matching 'other' must populate error_type.signature for disambiguation.
    """

    rate_limit = 'rate_limit'
    timeout = 'timeout'
    tool_call_failure = 'tool_call_failure'
    context_overflow = 'context_overflow'
    approval_denied = 'approval_denied'
    validation_error = 'validation_error'
    external_dependency_failure = 'external_dependency_failure'
    permission_denied = 'permission_denied'
    other = 'other'


class ExpectedOutcome(StrEnum):
    """
    The Final_Outcome slot of the frame: what terminal state this template aims to reach when its corrective action runs successfully. Instances (Events) at v058+ report the *actual* outcome separately.
    """

    recovered = 'recovered'
    partially_recovered = 'partially_recovered'
    escalated = 'escalated'
    aborted = 'aborted'


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: ResourceName
    ou_path: OuPath


class ErrorType(BaseModel):
    """
    Frame element 2: the failure category this frame matches. category is required; code and signature narrow further.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    category: ErrorCategory
    code: str | None = Field(None, max_length=128)
    """
    Vendor-specific or transport-level code (e.g., '429', 'InvalidRequest', 'context_length_exceeded').
    """
    signature: str | None = Field(None, max_length=1024)
    """
    Optional regex matched against the error message. Required when category='other'.
    """


class CorrectiveAction(BaseModel):
    """
    Frame element 3: the procedure to run when a matching failure occurs. summary is required free text; steps is an optional ordered list; policy_ref optionally points to a Policy that constrains execution (e.g., max_retries, backoff schedule).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    summary: str = Field(..., max_length=2048, min_length=1)
    steps: list[Step] | None = Field([], validate_default=True)
    policy_ref: ResourceName | None = None
    """
    Optional Policy resource constraining the corrective action (e.g., max_retries, backoff_seconds, circuit_breaker_after).
    """
    max_attempts: int | None = Field(3, ge=1, le=100)
    """
    Hard cap on how many times this frame's corrective action runs for a single triggering failure before escalation.
    """


class Spec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: DisplayName
    description: str | None = Field(None, max_length=2048)
    applicable_scope_ref: ScopeRef
    """
    Scope inside which this frame can be invoked. Frames are scope-attached so the same error category can have different recovery patterns at org root vs. a specific OU.
    """
    applies_to_processes: list[ResourceName] | None = Field([], validate_default=True)
    """
    Optional process refs (Agent / Skill / Workflow / MCPDeployment names) this frame is registered on. Empty = applies to any process within applicable_scope_ref.
    """
    action_attempted: ActionAttempted
    """
    Frame element 1: the kind of action this frame matches. summary is required free text; process_kind narrows by Process primitive's process_kind field if set; matcher_pattern is an optional regex applied to the action's structured payload.
    """
    error_type: ErrorType
    """
    Frame element 2: the failure category this frame matches. category is required; code and signature narrow further.
    """
    corrective_action: CorrectiveAction
    """
    Frame element 3: the procedure to run when a matching failure occurs. summary is required free text; steps is an optional ordered list; policy_ref optionally points to a Policy that constrains execution (e.g., max_retries, backoff schedule).
    """
    final_outcome: ExpectedOutcome
    escalation_ref: ResourceName | None = None
    """
    Optional FailureRecoveryFrame name to invoke when this frame's max_attempts is exhausted without reaching final_outcome. Cycles are detected at apply time.
    """
    provenance: Provenance | None = 'operator_authored'
    """
    Where this frame came from. v057 ships only operator_authored; distilled_from_episodic lights up at v058+ when consolidation can promote observation conventions into frames.
    """
    evidence_run_ids: list[Uuid] | None = Field([], validate_default=True)
    """
    Optional list of session/workflow_run UUIDs the frame was distilled from. Empty for operator_authored frames at v057.
    """


class FailureRecoveryFrame(BaseModel):
    """
    A stereotyped failure-recovery template per Fillmore's Frame Semantics. Each manifest binds the four canonical frame elements (Action_Attempted / Error_Type / Corrective_Action / Final_Outcome) to a specific recovery pattern an agent should follow when matching failures occur. Derivation: compose(Process[recovery_procedure], Policy[trigger_conditions], Scope[applicable_scope]). Frames are the procedural-memory unit Powerloom agents reach for when a tool call, validation, or external request fails — authored by operators at v057, distilled from episodic runs at v058+ via consolidation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    apiVersion: ApiVersion
    kind: Literal['FailureRecoveryFrame']
    metadata: Metadata
    spec: Spec
