# generated by datamodel-codegen:
#   filename:  type-definition.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ApiVersion(StrEnum):
    """
    v2.0.0 fixes the apiVersion to a single canonical form. No monorepo backward-compat alias.
    """

    powerloom_app_v2 = 'powerloom.app/v2'


class ResourceName(RootModel[str]):
    root: str = Field(
        ..., max_length=63, min_length=1, pattern='^[a-z0-9][a-z0-9-]{0,62}$'
    )
    """
    DNS-compatible slug. Lowercase letters, digits, hyphens; must start with alnum; 1–63 chars.
    """


class Uuid(RootModel[str]):
    root: str = Field(
        ...,
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )


class DisplayName(RootModel[str]):
    root: str = Field(..., max_length=255, min_length=1)


class OuPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})*$'
    )
    """
    Absolute OU path, e.g. /acme/engineering/platform.
    """


class AgentPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})+$'
    )
    """
    Absolute path to a resource: /{org}/{ou...}/{name}.
    """


class PrincipalRef(RootModel[str]):
    root: str = Field(..., pattern='^(user:[^\\s]+@[^\\s]+|group:/.+|agent:/.+)$')
    """
    One of 'user:<email>', 'group:<group_path>', or 'agent:<agent_path>'.
    """


class ScopeRef(RootModel[str]):
    root: str = Field(
        ..., max_length=128, min_length=2, pattern='^[a-z0-9][a-z0-9_.-]*[a-z0-9]$'
    )
    """
    Dotted-path reference to a Scope (e.g., 'home.research.infra'). Resolves within the containing OU.
    """


class PrimitiveRef(StrEnum):
    """
    Name of one of the six v2 root primitives. Used in compose-expression slot tags.
    """

    Entity = 'Entity'
    Event = 'Event'
    Relation = 'Relation'
    Process = 'Process'
    Scope = 'Scope'
    Policy = 'Policy'


class KindRef(RootModel[str]):
    root: str = Field(..., pattern='^[A-Z][A-Za-z0-9]*(\\.[a-z0-9][a-z0-9_-]*)*$')
    """
    Qualified kind name: either a stdlib kind (e.g. 'Agent', 'Workflow') or a user-composed kind in a namespace (e.g. 'legal.ContractClause').
    """


class ComposeSlot1(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef
    extends: KindRef | None = None
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot2(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef | None = None
    extends: KindRef
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot(RootModel[ComposeSlot1 | ComposeSlot2]):
    root: ComposeSlot1 | ComposeSlot2
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """


class TypeKind(StrEnum):
    """
    Coarse classification driving default memory-policy values: 'domain' (long-lived concepts, grammar emphasis), 'process' (action templates, procedural emphasis), 'event' (timestamped occurrences, lexicon emphasis), 'relation' (typed edges, both).
    """

    domain = 'domain'
    process = 'process'
    event = 'event'
    relation = 'relation'


class Grammar(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool | None = True
    decay_half_life_days: int | None = Field(180, ge=1, le=36500)
    """
    Half-life in days for grammar cell decay. Grammar tracks 'how this type composes' — typically slow decay (months).
    """


class Lexicon(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool | None = True
    retention_days: int | None = Field(60, ge=1, le=36500)
    """
    Hard retention window for instance rows. Older rows get archived (or distilled into grammar via consolidation).
    """
    max_rows: int | None = Field(10000, ge=100, le=10000000)
    """
    Soft cap on rows-per-type-per-scope. Older rows beyond this drop on next consolidation pass even if within retention_days.
    """


class Reinforcement(BaseModel):
    """
    Thresholds that trigger promotion from observation -> reinforced template (procedural memory) or lexicon -> grammar (semantic memory).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    promote_after_count: int | None = Field(5, ge=1, le=1000)
    min_outcome_signal: float | None = Field(0.7, ge=-1.0, le=1.0)


class ConceptStabilization(BaseModel):
    """
    v063+ — concept-stabilization thresholds. Set enabled=true once v063 ships; v061/v062 ignore the block.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool | None = False
    min_branch_diversity: int | None = Field(3, ge=1, le=100)
    """
    Number of distinct scopes that must reinforce before a concept is proposed for stabilization (per Chomskian R18).
    """


class MemoryBlock(BaseModel):
    """
    How memory accumulates for instances of this type. All fields optional; sensible defaults vary by type_kind.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    grammar: Grammar | None = None
    lexicon: Lexicon | None = None
    reinforcement: Reinforcement | None = None
    """
    Thresholds that trigger promotion from observation -> reinforced template (procedural memory) or lexicon -> grammar (semantic memory).
    """
    concept_stabilization: ConceptStabilization | None = None
    """
    v063+ — concept-stabilization thresholds. Set enabled=true once v063 ships; v061/v062 ignore the block.
    """


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: ResourceName
    ou_path: OuPath


class Spec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: DisplayName
    description: str | None = Field(None, max_length=2048)
    type_kind: TypeKind
    type_namespace: str | None = Field(
        None, max_length=128, min_length=2, pattern='^[a-z0-9][a-z0-9_.-]*[a-z0-9]$'
    )
    """
    Optional dotted namespace. Defaults to the OU's slug-path when omitted (e.g. an OU at /acme/legal yields namespace 'acme.legal'). Prevents cross-branch type-name collisions.
    """
    applies_to_scope_ref: ScopeRef
    """
    Scope inside which this type is recognized (e.g. 'legal.contracts'). Memory cells key on (type, scope_id) so the same type name can carry different grammar/lexicon in different scopes.
    """
    extends_type_ref: ResourceName | None = None
    """
    Optional parent TypeDefinition name. Inherited types share grammar (read-up; child cells are deltas) but have independent lexicon. v062's query API surfaces the merged grammar.
    """
    memory: MemoryBlock | None = Field({}, validate_default=True)


class TypeDefinition(BaseModel):
    """
    Declares a named type that the engine accumulates memory around. Each TypeDefinition manifest binds a name to a memory-governance policy: how grammar (how this type composes with others) and lexicon (specific instance content + outcome signals) are tracked, retained, and decayed. v061 ships the authoring surface and the empty grammar/lexicon tables; v062 wires the consolidation pipeline that fills them; v063 lights up concept stabilization on top. Derivation: compose(Entity[type_identity], Policy[memory_governance]).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    apiVersion: ApiVersion
    kind: Literal['TypeDefinition']
    metadata: Metadata
    spec: Spec
