"""Tests for the v0.6.1 X-Powerloom-Schema-Version header injection +
426 Upgrade Required formatting.

Covers:
  - Client injects the header on every request, sourced from
    loomcli.schema.SCHEMA_VERSION (no flag, no env var — always on)
  - 426 responses with the engine's body shape
    {error.detail.{supported_versions, client_sent}} are formatted into
    a clear "engine rejected schema version X; supported: [...]" line
  - 426 responses without that shape fall through to the default detail
    extractor (back-compat with non-engine 426s in the wild)

Companion to engine `core/schema_version_check.py` + the middleware in
`api/powerloom_api/main.py`.
"""
from __future__ import annotations

import httpx
import pytest

from loomcli.client import (
    PowerloomApiError,
    PowerloomClient,
    _format_version_mismatch,
)
from loomcli.config import RuntimeConfig
from loomcli.schema import SCHEMA_VERSION


# ---------------------------------------------------------------------------
# Header injection — always-on
# ---------------------------------------------------------------------------


def test_client_sends_schema_version_header():
    cfg = RuntimeConfig(api_base_url="https://test.example.com", access_token="tok")
    client = PowerloomClient(cfg)
    try:
        assert (
            client._http.headers.get("X-Powerloom-Schema-Version") == SCHEMA_VERSION
        )
    finally:
        client.close()


def test_schema_version_value_matches_loomcli_package_version():
    """The header value is sourced from the same SCHEMA_VERSION constant
    that lives in `loomcli.schema.__init__.py` — auto-generated by
    `scripts/generate_schema_package.py` from `schema/v2/VERSION`. So
    a schema bump propagates without code changes here."""
    cfg = RuntimeConfig(api_base_url="https://test.example.com", access_token="tok")
    client = PowerloomClient(cfg)
    try:
        sent = client._http.headers["X-Powerloom-Schema-Version"]
        assert sent == SCHEMA_VERSION
        # Sanity: SCHEMA_VERSION is non-empty + looks vaguely semver-like.
        assert sent
        assert sent[0].isdigit() or sent.startswith("v")
    finally:
        client.close()


def test_header_present_even_without_token():
    """Unauthenticated request paths (login, etc.) still send the header
    so the engine can 426 a wildly out-of-date CLI before it even tries
    to authenticate."""
    cfg = RuntimeConfig(api_base_url="https://test.example.com", access_token=None)
    client = PowerloomClient(cfg)
    try:
        assert "X-Powerloom-Schema-Version" in client._http.headers
        # And no Authorization header (back-compat sanity).
        assert "Authorization" not in client._http.headers
    finally:
        client.close()


def test_header_alongside_approval_justification():
    """v0.5.3 + v0.6.1 headers coexist — both flow through."""
    cfg = RuntimeConfig(
        api_base_url="https://test.example.com",
        access_token="tok",
        approval_justification="bootstrap",
    )
    client = PowerloomClient(cfg)
    try:
        h = client._http.headers
        assert h["X-Powerloom-Schema-Version"] == SCHEMA_VERSION
        assert h["X-Approval-Justification"] == "bootstrap"
        assert h["Authorization"] == "Bearer tok"
    finally:
        client.close()


# ---------------------------------------------------------------------------
# 426 formatting — pure unit
# ---------------------------------------------------------------------------


def test_format_version_mismatch_shapes_message():
    body = {
        "error": {
            "code": "schema_version_unsupported",
            "message": "engine message...",
            "status": 426,
            "detail": {
                "supported_versions": ["v1.2.0", "v2"],
                "client_sent": "v3",
            },
        }
    }
    msg = _format_version_mismatch(body)
    assert msg is not None
    assert "v3" in msg
    assert "v1.2.0" in msg
    assert "v2" in msg
    assert "upgrade" in msg.lower()


def test_format_version_mismatch_returns_none_for_unrelated_426():
    """A 426 from some other source (proxy, gateway) without the engine's
    expected detail shape falls through to the default extractor."""
    assert _format_version_mismatch({"error": {"message": "old proxy says no"}}) is None
    assert _format_version_mismatch({"detail": "raw fastapi 426"}) is None
    assert _format_version_mismatch({}) is None
    assert _format_version_mismatch("not even a dict") is None
    assert _format_version_mismatch(None) is None


def test_format_version_mismatch_requires_both_fields():
    """Partial detail (only supported_versions, only client_sent) doesn't
    qualify — fall back to default."""
    only_supported = {
        "error": {"detail": {"supported_versions": ["v2"]}}
    }
    only_sent = {"error": {"detail": {"client_sent": "v3"}}}
    assert _format_version_mismatch(only_supported) is None
    assert _format_version_mismatch(only_sent) is None


# ---------------------------------------------------------------------------
# End-to-end via mocked HTTP — confirms PowerloomApiError carries the
# formatted detail when the engine 426s.
# ---------------------------------------------------------------------------


class _StubResponse:
    def __init__(self, status_code: int, body: dict):
        self.status_code = status_code
        self._body = body
        self.text = str(body)

    def json(self):
        return self._body


def test_426_mismatch_message_propagates_through_error(monkeypatch):
    """When the engine returns a 426 with the canonical body shape, the
    PowerloomApiError's message includes the formatted upgrade hint."""
    cfg = RuntimeConfig(api_base_url="https://test.example.com", access_token="tok")
    client = PowerloomClient(cfg)
    try:
        canonical_body = {
            "error": {
                "code": "schema_version_unsupported",
                "message": "engine reject",
                "status": 426,
                "detail": {
                    "supported_versions": ["v1.2.0", "v2"],
                    "client_sent": "v3",
                },
            }
        }

        def fake_request(*_args, **_kwargs):
            return _StubResponse(426, canonical_body)

        monkeypatch.setattr(client._http, "request", fake_request)

        with pytest.raises(PowerloomApiError) as exc_info:
            client.get("/agents")

        assert exc_info.value.status_code == 426
        # The formatted message wins over the raw engine `message`.
        assert "v3" in str(exc_info.value)
        assert "supported" in str(exc_info.value).lower()
        assert "v2" in str(exc_info.value)
        # Body is preserved for callers who want the raw detail.
        assert exc_info.value.body == canonical_body
    finally:
        client.close()


def test_426_with_unrecognized_body_falls_back_to_generic_detail(monkeypatch):
    cfg = RuntimeConfig(api_base_url="https://test.example.com", access_token="tok")
    client = PowerloomClient(cfg)
    try:
        body = {"error": {"message": "different 426 shape"}}

        def fake_request(*_args, **_kwargs):
            return _StubResponse(426, body)

        monkeypatch.setattr(client._http, "request", fake_request)

        with pytest.raises(PowerloomApiError) as exc_info:
            client.get("/agents")

        assert exc_info.value.status_code == 426
        # Falls back to the engine's `error.message` since detail shape
        # didn't match the canonical version-mismatch payload.
        assert "different 426 shape" in str(exc_info.value)
    finally:
        client.close()
