"""Generated by scripts/generate_schema_package.py. Do not edit."""

from . import entity  # noqa: F401
from . import event  # noqa: F401
from . import policy  # noqa: F401
from . import process  # noqa: F401
from . import relation  # noqa: F401
from . import scope  # noqa: F401
