# generated by datamodel-codegen:
#   filename:  scope.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ScopeType(StrEnum):
    """
    Tier of the scope hierarchy. Defaults to 'custom'. Organization + OU stdlib derivations pin this via their kind dispatch; Scope primitives authored directly need only set it when distinguishing from custom.
    """

    organization = 'organization'
    ou = 'ou'
    project = 'project'
    session = 'session'
    workflow_run = 'workflow_run'
    custom = 'custom'


class InheritanceMode(StrEnum):
    """
    How memory from parent flows in.
    """

    full = 'full'
    isolated = 'isolated'
    selective = 'selective'


class MemoryKind(StrEnum):
    grammar = 'grammar'
    lexicon = 'lexicon'
    procedural = 'procedural'
    concepts = 'concepts'


class SelectiveInheritance(BaseModel):
    """
    Only consulted when inheritance_mode=selective.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    from_types: list[str] | None = None
    memory_kinds: list[MemoryKind] | None = None


class RetentionOverride(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decay_days: int | None = Field(None, ge=1, le=3650)
    forget_after_days: int | None = Field(None, ge=1, le=3650)


class Spec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scope_type: ScopeType | None = 'custom'
    """
    Tier of the scope hierarchy. Defaults to 'custom'. Organization + OU stdlib derivations pin this via their kind dispatch; Scope primitives authored directly need only set it when distinguishing from custom.
    """
    parent_scope_ref: str | None = None
    """
    Dotted-path reference to parent scope. Null = root of a tier.
    """
    inheritance_mode: InheritanceMode | None = 'full'
    """
    How memory from parent flows in.
    """
    selective_inheritance: SelectiveInheritance | None = None
    """
    Only consulted when inheritance_mode=selective.
    """
    retention_override: RetentionOverride | None = None


class ApiVersion(StrEnum):
    """
    v2.0.0 fixes the apiVersion to a single canonical form. No monorepo backward-compat alias.
    """

    powerloom_app_v2 = 'powerloom.app/v2'


class ResourceName(RootModel[str]):
    root: str = Field(
        ..., max_length=63, min_length=1, pattern='^[a-z0-9][a-z0-9-]{0,62}$'
    )
    """
    DNS-compatible slug. Lowercase letters, digits, hyphens; must start with alnum; 1–63 chars.
    """


class Uuid(RootModel[str]):
    root: str = Field(
        ...,
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )


class DisplayName(RootModel[str]):
    root: str = Field(..., max_length=255, min_length=1)


class OuPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})*$'
    )
    """
    Absolute OU path, e.g. /acme/engineering/platform.
    """


class AgentPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})+$'
    )
    """
    Absolute path to a resource: /{org}/{ou...}/{name}.
    """


class PrincipalRef(RootModel[str]):
    root: str = Field(..., pattern='^(user:[^\\s]+@[^\\s]+|group:/.+|agent:/.+)$')
    """
    One of 'user:<email>', 'group:<group_path>', or 'agent:<agent_path>'.
    """


class ScopeRef(RootModel[str]):
    root: str = Field(
        ..., max_length=128, min_length=2, pattern='^[a-z0-9][a-z0-9_.-]*[a-z0-9]$'
    )
    """
    Dotted-path reference to a Scope (e.g., 'home.research.infra'). Resolves within the containing OU.
    """


class PrimitiveRef(StrEnum):
    """
    Name of one of the six v2 root primitives. Used in compose-expression slot tags.
    """

    Entity = 'Entity'
    Event = 'Event'
    Relation = 'Relation'
    Process = 'Process'
    Scope = 'Scope'
    Policy = 'Policy'


class KindRef(RootModel[str]):
    root: str = Field(..., pattern='^[A-Z][A-Za-z0-9]*(\\.[a-z0-9][a-z0-9_-]*)*$')
    """
    Qualified kind name: either a stdlib kind (e.g. 'Agent', 'Workflow') or a user-composed kind in a namespace (e.g. 'legal.ContractClause').
    """


class ComposeSlot1(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef
    extends: KindRef | None = None
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot2(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef | None = None
    extends: KindRef
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot(RootModel[ComposeSlot1 | ComposeSlot2]):
    root: ComposeSlot1 | ComposeSlot2
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ..., max_length=128, min_length=2, pattern='^[a-z0-9][a-z0-9_.-]*[a-z0-9]$'
    )
    """
    Stable scope identifier. Dots allowed for hierarchical naming.
    """
    ou_path: OuPath | None = None
    """
    Containing OU (path form — preferred in v2).
    """
    ou_id: Uuid | None = None
    """
    Containing OU (UUID form — preserved for v1.2.0 shape parity).
    """
    display_name: DisplayName | None = None
    description: str | None = Field(None, max_length=2048)


class Scope(BaseModel):
    """
    A boundary that policies apply within — spatial or logical. One of the six v2 root primitives. Scope was additive in v1.2.0; v2.0.0 promotes it to primitive status with identical shape. Organizations and OUs are both Scope instances with specific scope_type values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    apiVersion: ApiVersion
    kind: Literal['Scope']
    metadata: Metadata
    spec: Spec
