#!/usr/bin/env python3
"""Generate `loomcli.schema` Pydantic models from schema/v2/*.json.

Run: `python scripts/generate_schema_package.py`
Output: `loomcli/schema/v2/{primitives,stdlib,compose,common}.py`

The generated package is committed to the repo — CI verifies the
output matches by re-running this script and diffing. Do NOT edit the
generated files by hand; edit the source JSON Schema instead.

Uses datamodel-code-generator (https://github.com/koxudaxi/datamodel-code-generator).
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_V2 = ROOT / "schema" / "v2"
OUT = ROOT / "loomcli" / "schema" / "v2"

# (input-json, output-py, class-prefix)
_TARGETS = [
    (SCHEMA_V2 / "common.schema.json", OUT / "common.py", "Common"),
    (SCHEMA_V2 / "compose.schema.json", OUT / "compose.py", "Compose"),
]
_TARGETS += [
    (p, OUT / "primitives" / f"{p.stem.replace('.schema', '')}.py", p.stem.split('.')[0].capitalize())
    for p in sorted((SCHEMA_V2 / "primitives").glob("*.schema.json"))
]
_TARGETS += [
    (p, OUT / "stdlib" / f"{p.stem.replace('.schema', '').replace('-', '_')}.py", p.stem.split('.')[0].replace('-', '_').capitalize())
    for p in sorted((SCHEMA_V2 / "stdlib").glob("*.schema.json"))
]


def _clean() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    (OUT / "primitives").mkdir()
    (OUT / "stdlib").mkdir()


def _generate(src: Path, dst: Path, class_name: str) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable, "-m", "datamodel_code_generator",
        "--input", str(src),
        "--input-file-type", "jsonschema",
        "--output", str(dst),
        "--output-model-type", "pydantic_v2.BaseModel",
        "--target-python-version", "3.11",
        "--use-schema-description",
        "--use-field-description",
        "--disable-timestamp",
        "--class-name", class_name,
        "--field-constraints",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"[FAIL] {src.name}:")
        print(result.stderr)
        sys.exit(result.returncode)
    print(f"[ok] {src.relative_to(ROOT)} -> {dst.relative_to(ROOT)}")


def _write_init(dir_: Path, names: list[str]) -> None:
    """Tiny re-export __init__.py for each subpackage."""
    body = '"""Generated by scripts/generate_schema_package.py. Do not edit."""\n\n'
    for n in names:
        body += f"from . import {n}  # noqa: F401\n"
    (dir_ / "__init__.py").write_text(body, encoding="utf-8")


def main() -> None:
    _clean()

    # Generate each model file.
    for src, dst, cls in _TARGETS:
        _generate(src, dst, cls)

    # Write subpackage __init__.py files.
    prim_names = sorted(p.stem for p in (OUT / "primitives").glob("*.py") if p.stem != "__init__")
    std_names = sorted(p.stem for p in (OUT / "stdlib").glob("*.py") if p.stem != "__init__")
    _write_init(OUT / "primitives", prim_names)
    _write_init(OUT / "stdlib", std_names)

    # Root loomcli.schema.v2 __init__.py.
    root_body = (
        '"""Generated Pydantic models for Powerloom v2.0.0 schema.\n'
        '\n'
        'Source: schema/v2/*.schema.json (authoritative).\n'
        'Regenerate: `python scripts/generate_schema_package.py`.\n'
        'Do NOT edit the generated files by hand.\n'
        '"""\n'
        '\n'
        'from . import common, compose, primitives, stdlib  # noqa: F401\n'
    )
    (OUT / "__init__.py").write_text(root_body, encoding="utf-8")

    # loomcli.schema __init__.py — version marker, sourced from schema/v2/VERSION.
    parent = OUT.parent
    schema_version = (SCHEMA_V2 / "VERSION").read_text(encoding="utf-8").strip()
    (parent / "__init__.py").write_text(
        '"""Versioned Pydantic schema models for Powerloom manifests."""\n'
        '\n'
        f'SCHEMA_VERSION = "{schema_version}"\n'
        '\n'
        'from . import v2  # noqa: F401\n',
        encoding="utf-8",
    )

    print(f"\n[done] Generated {len(_TARGETS)} modules into {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
