# generated by datamodel-codegen:
#   filename:  compose.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ApiVersion(StrEnum):
    """
    v2.0.0 fixes the apiVersion to a single canonical form. No monorepo backward-compat alias.
    """

    powerloom_app_v2 = 'powerloom.app/v2'


class ResourceName(RootModel[str]):
    root: str = Field(
        ..., max_length=63, min_length=1, pattern='^[a-z0-9][a-z0-9-]{0,62}$'
    )
    """
    DNS-compatible slug. Lowercase letters, digits, hyphens; must start with alnum; 1–63 chars.
    """


class Uuid(RootModel[str]):
    root: str = Field(
        ...,
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )


class DisplayName(RootModel[str]):
    root: str = Field(..., max_length=255, min_length=1)


class OuPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})*$'
    )
    """
    Absolute OU path, e.g. /acme/engineering/platform.
    """


class AgentPath(RootModel[str]):
    root: str = Field(
        ..., pattern='^/([a-z0-9][a-z0-9-]{0,62})(/[a-z0-9][a-z0-9-]{0,62})+$'
    )
    """
    Absolute path to a resource: /{org}/{ou...}/{name}.
    """


class PrincipalRef(RootModel[str]):
    root: str = Field(..., pattern='^(user:[^\\s]+@[^\\s]+|group:/.+|agent:/.+)$')
    """
    One of 'user:<email>', 'group:<group_path>', or 'agent:<agent_path>'.
    """


class ScopeRef(RootModel[str]):
    root: str = Field(
        ..., max_length=128, min_length=2, pattern='^[a-z0-9][a-z0-9_.-]*[a-z0-9]$'
    )
    """
    Dotted-path reference to a Scope (e.g., 'home.research.infra'). Resolves within the containing OU.
    """


class PrimitiveRef(StrEnum):
    """
    Name of one of the six v2 root primitives. Used in compose-expression slot tags.
    """

    Entity = 'Entity'
    Event = 'Event'
    Relation = 'Relation'
    Process = 'Process'
    Scope = 'Scope'
    Policy = 'Policy'


class KindRef(RootModel[str]):
    root: str = Field(..., pattern='^[A-Z][A-Za-z0-9]*(\\.[a-z0-9][a-z0-9_-]*)*$')
    """
    Qualified kind name: either a stdlib kind (e.g. 'Agent', 'Workflow') or a user-composed kind in a namespace (e.g. 'legal.ContractClause').
    """


class ComposeSlot1(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef
    extends: KindRef | None = None
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot2(BaseModel):
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    primitive: PrimitiveRef | None = None
    extends: KindRef
    role: str | None = Field(None, pattern='^[a-z][a-z0-9_]*$')
    """
    Optional role tag disambiguates multiple slots of the same primitive type (e.g., two Policy slots with roles 'runtime' and 'access').
    """
    fields: dict[str, Any] | None = None
    """
    Field values for this slot. Validated against the referenced primitive or kind schema.
    """


class ComposeSlot(RootModel[ComposeSlot1 | ComposeSlot2]):
    root: ComposeSlot1 | ComposeSlot2
    """
    A single slot in a compose-expression. References one primitive (or extends a stdlib kind), optionally tagged with a role and populated with field values.
    """


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., pattern='^[A-Z][A-Za-z0-9]*$')
    """
    The composed kind's name. Capital-first, no underscores (e.g. 'ContractClause', 'CodeReviewSession').
    """
    namespace: str | None = Field(
        None, max_length=128, min_length=2, pattern='^[a-z0-9][a-z0-9_.-]*[a-z0-9]$'
    )
    """
    Dotted namespace for the composed kind (e.g. 'legal.acme'). Prevents cross-branch name collisions.
    """
    display_name: DisplayName | None = None
    description: str | None = Field(None, max_length=2048)


class Spec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    compose: list[ComposeSlot] = Field(..., max_length=8, min_length=1)
    """
    The composition expression — a list of primitive or stdlib-extension slots. Slots merge into a single kind. Field collisions require !override on one side.
    """
    interface: dict[str, Any] | None = None
    """
    Declared interface for this kind — fields exposed to other composables. Used by interface-check at weave lint time.
    """
    constraints: list[str] | None = None
    """
    Optional validation rules (e.g., 'exactly-one-Policy-slot', 'all-effects-must-resolve'). Domain-specific.
    """


class Compose(BaseModel):
    """
    The `compose` operator — authoring surface for user-defined derivations. Lets operators declare new kinds as compositions of the 6 primitives (or extensions of stdlib kinds). See docs/compose-from-primitives.md for the authoring guide.

    Policy slot authoring: `policy_type` is a FREE-FORM STRING — you pick a value that names the policy's domain (e.g. 'legal_constraint', 'escalation_rules', 'treatment_rules', 'regulatory_screening'). It is not an enum. Put the policy's concrete rules under `statement`, `applies_to` lists the scope_refs the policy governs, and `exceptions` lists scopes where it doesn't apply. Example: { primitive: 'Policy', role: 'escalation', fields: { policy_type: 'escalation_rules', statement: {...}, applies_to: ['support.tier1'] } }.

    Entity slots hold attributes keyed by your domain names. Event slots carry `event_type` (free-form, e.g. 'result_recorded'). Relation slots carry `relation_type` ('cites', 'belongs_to', 'measures') + `source_entity_id` + `target_entity_id`.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    apiVersion: ApiVersion
    kind: Literal['Compose']
    metadata: Metadata
    spec: Spec
